# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow validates the packaging of the Java project using Maven.

name: Packaging check Maven

on: pull_request


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven wget
      - name: Download and install jhighs
        run: |
          if wget https://github.com/jessenagel/JHiGHS/releases/download/v0.1.1/jhighs-0.1.1.jar; then
            echo "Download successful"
            ls -la jhighs-0.1.1.jar
          else
            echo "Download failed"
            exit 1
          fi
          
          mvn install:install-file \
            -Dfile=jhighs-0.1.1.jar \
            -DgroupId=nl.jessenagel.optimization \
            -DartifactId=jhighs \
            -Dversion=0.1.1 \
            -Dpackaging=jar

      - name: Verify jhighs installation
        run: |
          mvn dependency:list | grep jhighs || echo "jhighs not found in dependencies"
          ls -la ~/.m2/repository/org/jessenagel/jhighs/ || echo "jhighs not in local repository"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install HiGHS
        run: |
          curl -sL https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0%2B0/HiGHSstatic.v1.10.0.x86_64-linux-gnu-cxx03.tar.gz -o highs.tar.gz
          mkdir /opt/HiGHS
          tar -xf highs.tar.gz -C /opt/HiGHS
          rm highs.tar.gz
          mkdir -p $HOME/bin
          ln -s /opt/HiGHS/bin/highs $HOME/bin/highs
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Build with Maven
        run: mvn -B package --file pom.xml