name: Trigger Maven Repository Update

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger-maven-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get release info
      id: release
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "SUBMODULE=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

    - name: Trigger Optimization repository deployment
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.OPTIMIZATION_REPO_TOKEN }}
        repository: ${{ github.repository_owner }}/Optimization
        event-type: submodule-release
        client-payload: |
          {
            "submodule": "${{ steps.release.outputs.SUBMODULE }}",
            "version": "${{ steps.release.outputs.VERSION }}",
            "repository": "${{ github.repository }}",
            "release_url": "${{ github.event.release.html_url }}"
          }
